console.log('Olá mundo!');
console.log('Tudo bem?');
console.log('tudo');
console.log('kajdh');
console.log('Olá mundo!');
console.log('Tudo bem?');
console.log('tudo');
console.log('kajdh');
console.log('Olá mundo!');
console.log('Tudo bem?');
console.log('tudo');
console.log('kajdh');
console.log('Olá mundo!');
console.log('Tudo bem?');
console.log('tudo');
console.log('kajdh');
console.log('Olá mundo!');
console.log('Tudo bem?');
console.log('tudo');
console.log('kajdh');
console.log('Olá mundo!');
console.log('Tudo bem?');
console.log('tudo');
console.log('kajdh');

console.log('Olá mundo!');
console.log('Tudo bem?');
console.log('tudo');
console.log('kajdh');
console.log('Olá mundo!');
console.log('Tudo bem?');
console.log('tudo');
console.log('kajdh');
console.log('Olá mundo!');
console.log('Tudo bem?');
console.log('tudo');
console.log('kajdh');
console.log('Olá mundo!');
console.log('Tudo bem?');
console.log('tudo');
console.log('kajdh');
console.log('Olá mundo!');
console.log('Tudo bem?');
console.log('tudo');
console.log('kajdh');

console.log('Olá mundo!');
console.log('Tudo bem?');
console.log('tudo');
console.log('kajdh');console.log('Olá mundo!');
console.log('Tudo bem?');
console.log('tudo');
console.log('kajdh');

